---
- name: Prepare aptitude
  become: yes
  shell: apt update && apt install -qq -y aptitude
  ignore_errors: yes

- name: Upgrade packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Install packages
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - build-essential
    - gzip
    - pxz
    - vim
    - git
    - ruby
    - ruby-dev
    - python-psycopg2
    - python-mysqldb

- name: Install Bundler
  gem:
    name: bundler
    user_install: no

- name: Add locale ja_JP.UTF-8
  become: yes
  shell: |
    sed -i -e 's/^# ja_JP\.UTF-8/ja_JP.UTF-8/' /etc/locale.gen
    locale-gen
    update-locale LANG=ja_JP.UTF-8
