---
- name: Create new user for MariaDB
  mysql_user:
    name: redmine
    password: redmine
    priv: '*.*:ALL'
    state: present

- name: Create new database for MariaDB
  mysql_db:
    name: redmine
    encoding: utf8
    state: present

- name: Copy MariaDB dump file
  copy:
    src: benchmark-mariadb.dump.sql.xz
    dest: /tmp/benchmark-mariadb.dump.sql.xz

- name: Import MariaDB dump
  become: yes
  shell: pxz -dc /tmp/benchmark-mariadb.dump.sql.xz | mysql redmine
  # mysql_db:
  #   name: redmine
  #   state: import
  #   target: /tmp/benchmark-mariadb.dump.sql.xz
