---
- name: Create user for Redmine
  user:
    name: "{{ redmine_user }}"

- name: Install pacakges for Redmine
  apt:
    name: "{{ item }}"
  with_items:
    - gcc
    - make
    - pkg-config
    - curl
    - libmariadbclient-dev
    - postgresql-server-dev-all
    - libmagickwand-6.q16-dev
    - imagemagick
    - ruby-dev

- name: Install Redmine
  become: yes
  git:
    repo: "{{ redmine_repo_url }}"
    dest: "/home/{{ redmine_user }}/redmine"
    version: "{{ redmine_version }}"

- name: Change Redmine owner
  become: yes
  file:
    path: "/home/{{ redmine_user }}/redmine"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_user }}"
    recurse: yes
    state: directory

- name: Create database.yml
  become: yes
  template:
    src: "database.yml.{{ database_adapter }}.j2"
    dest: "/home/{{ redmine_user }}/redmine/config/database.yml"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_user }}"
    mode: 0644

- name: Create configuration.yml
  become: yes
  template:
    src: configuration.yml.j2
    dest: "/home/{{ redmine_user }}/redmine/config/configuration.yml"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_user }}"
    mode: 0644

- name: Install plugin
  become: yes
  git:
    repo: https://github.com/okkez/redmine_full_text_search.git
    dest: "/home/{{ redmine_user }}/redmine/plugins/full_text_search"
    version: "{{ full_text_search_version }}"
  when: use_full_text_search

- name: Change owner of plugins
  file:
    path: "/home/{{ redmine_user }}/redmine/plugins"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_user }}"
    recurse: yes
    state: directory

- name: Install Gem packages
  become_user: "{{ redmine_user }}"
  shell: bundle install --path vendor/bundle
  vars:
    ansible_ssh_pipelining: true
  args:
    chdir: "/home/{{ redmine_user }}/redmine"

- name: Setup Redmine
  become_user: "{{ redmine_user }}"
  vars:
    ansible_ssh_pipelining: true
  shell: |
    bin/rake generate_secret_token
    bin/rake db:migrate RAILS_ENV=production
    bin/rake redmine:plugins:migrate RAILS_ENV=production
    bin/rake tmp:cache:clear
    bin/rake tmp:sessions:clear
  args:
    chdir: "/home/{{ redmine_user }}/redmine"

