---
- name: Git clone benchmark scripts
  become: no
  git:
    repo: https://github.com/okkez/redmine_full_text_search-benchmark.git
    dest: ~/redmine_full_text_search-benchmark
    depth: 1
    force: yes

- name: Bundle install
  become: no
  shell: bundle install --path vendor/bundle
  args:
    chdir: ~/redmine_full_text_search-benchmark/benchmark
