---
- hosts: servers
  become: yes
  vars:
    redmine_user: redmine
    redmine_version: 3.4.2
    redmine_repo_url: https://github.com/redmine/redmine
    database_adapter: postgresql
    ruby_api_version: 2.3.0
    passenger_version: 5.1.6
  roles:
    - base
    - groonga
    - postgresql
    - mariadb
    - redmine
    - httpd
