---
- hosts: servers
  become: yes
  roles:
    - base
    - groonga
    - postgresql
    - mariadb
    - redmine
    - httpd

- hosts: log
  become: yes
  roles:
    - base
    - fluentd
    - benchmark
