---
- name: Create PostgreSQL user for Redmine
  become: postgres
  postgresql_user:
    name: redmine
    password: redmine

- name: Create PostgreSQL database for Redmine
  postgresql_db:
    name: redmine
    encoding: UTF-8
    lc_collate: ja_JP.UTF-8
    lc_ctype:  ja_JP.UTF-8
    template: template0

- name: Check PostgreSQL dump file
  stat:
    path: /tmp/dump.sql.gz
  register: dump.exists
  changed_when: false
  check_mode: no

- name: Import data from dump file (PostgreSQL)
  become: postgres
  shell: zcat /tmp/dump.sql.gz | psql redmine
  when: dump.exists

- name: Grant usage to redmine
  become: postgres
  postgresql_privs:
    database: redmine
    state: present
    schema: pgroonga
    privs: USAGE
    roles: redmine
    grant_option: yes
