---
- name: Create PostgreSQL user for Redmine
  become_user: postgres
  postgresql_user:
    name: redmine
    password: redmine
  vars:
    ansible_ssh_pipelining: true

- name: Create PostgreSQL database for Redmine
  become_user: postgres
  postgresql_db:
    name: redmine
    encoding: UTF-8
  vars:
    ansible_ssh_pipelining: true

- name: Check PostgreSQL dump file
  stat:
    path: //tmp/benchmark-porgresql.dump.sql.xz
  register: dump.exists
  changed_when: false
  check_mode: no

# - name: Import data from dump file (PostgreSQL)
#   become_user: postgres
#   shell: pixz -dc /tmp/benchmark-porgresql.dump.sql.xz | psql redmine
#   when: dump.exists

- name: Create extension PGroonga
  become_user: postgres
  postgresql_ext:
    db: redmine
    name: pgroonga
  vars:
    ansible_ssh_pipelining: true

- name: Grant usage to redmine
  become_user: postgres
  postgresql_privs:
    database: redmine
    state: present
    privs: USAGE
    roles: redmine
    type: schema
    objs: pgroonga
    grant_option: yes
  vars:
    ansible_ssh_pipelining: true
