---
- name: Create PostgreSQL user for Redmine
  become_user: postgres
  postgresql_user:
    name: redmine
    password: redmine
  vars:
    ansible_ssh_pipelining: true

- name: Drop PostgreSQL database for Redmine
  become_user: postgres
  postgresql_db:
    name: redmine
    state: absent
  vars:
    ansible_ssh_pipelining: true

- name: Create PostgreSQL database for Redmine
  become_user: postgres
  postgresql_db:
    name: redmine
    encoding: UTF-8
    owner: redmine
  vars:
    ansible_ssh_pipelining: true

- name: Copy PostgreSQL dump file
  copy:
    src: benchmark-postgresql.dump.sql.xz
    dest: /tmp/benchmark-postgresql.dump.sql.xz

- name: Import PostgreSQL dump
  become_user: postgres
  shell: pxz -dc /tmp/benchmark-postgresql.dump.sql.xz | psql redmine
  register: psql_result
  vars:
    ansible_ssh_pipelining: true

- name: Import PostgreSQL dump (stdout)
  debug:
    var: psql_result.stdout_lines

- name: Import PostgreSQL dump (stderr)
  debug:
    var: psql_result.stderr_lines

- name: Create extension PGroonga
  become_user: postgres
  postgresql_ext:
    db: redmine
    name: pgroonga
  vars:
    ansible_ssh_pipelining: true
  when: use_full_text_search

- name: Grant usage to redmine
  become_user: postgres
  postgresql_privs:
    database: redmine
    state: present
    privs: USAGE
    roles: redmine
    type: schema
    objs: pgroonga
    grant_option: yes
  vars:
    ansible_ssh_pipelining: true
  when: use_full_text_search
